### ISSUE TITLE
Issues with Docker setup

### ISSUE THREAD

**Issue by victorhora** [SkierPGP/Skier-docker#1]
Hello,

I'm having a few problems trying to deploy an instance of Skier following the "Setup instructions" here.

The skier-base successfully compiled and run all the way to the end, but the skier image build is failing to compile.

The first issue is a failure of the "keybase verify" step as described on the Dockerfile:
# Verify sources

RUN keybase dir verify --assert github:sundwarf --assert reddit:octagonclock --assert dns:sundwarf.me /var/skier/pyapp 

I've noticed that the error could be related to the DNS check of keybase (--assert dns:sundwarf.me), so I've edited the file and omitted that to try again. 

The second issue seems to be related of the proper setup of a PostgreSQL database on the docker instance as suggested by the logs on the end of this post.

I've considered on trying to fix this myself (or overcoming by "forcing" a setup of PostgreSQL database locally), but as I'm pretty new to Dockers and my Python skills are almost none, I thought that you might come up quickly with a fix for this issue or suggest what could be wrong with my setup. :)

Btw, I'm running Ubuntu 15.10 if that matters...

Thanks in advance!

-------------- LOGS --------------

Step 11 : WORKDIR /var/skier/pyapp
 ---> Running in 7164015f1942
 ---> 84cab3035182
Removing intermediate container 7164015f1942
Step 12 : RUN /var/skier/pyapp/manager.py db upgrade
 ---> Running in bd222da8c857
Traceback (most recent call last):
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.**connect()
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(_cargs, *_cparams)
  File "/var/skier/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(_cargs, *_cparams)
  File "/var/skier/venv/lib/python3.4/site-packages/psycopg2/__init**.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

-------------- LOGS --------------

**Comment by Fuyukai** [comment]
Oh, whoops, I haven't actually updated this to verify my new dns sites.  

There is a way to use the host connection, let me commit it quickly.
